### ISSUE TITLE
Not even a single package mentions php version support!

### ISSUE THREAD

**Issue by drnkwati** [PHPixie/Framework#2]
I have check every where almost. Even ok no the docs of the main website but can't find the php version support for this framework. 
Please do include that information in the composer files as well.
Thanks

**Comment by dracony** [comment]
You can find th ebuild matrix with the unit tests. Packages work on PHP 5.4+, so basically any non-deprecated version is ok. Compatibility is important to this project. But it's a good idea to add it to composer files, will do!
